# Setup
title:        OpenDelays Data Visualization
tagline:      [...]
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Blabla
  url:        http://yourhomepage.com 

# Gems
plugins: [jekyll-include-cache]

#Others
markdown: kramdown

remote_theme: "mmistakes/minimal-mistakes@4.24.0"